### ISSUE TITLE
SSLize

### ISSUE THREAD

**Issue by adamamyl** [no2id/meta-infra#2]
https://letsencrypt.org/howitworks/

**Comment by adamamyl** [comment]
Sorted! Next thing to do is to cron the renewals, once worked out best way to do this…

**Comment by jezuk** [comment]
Hi guys,

FYI you are missing a redirect from http://www.no2id.net to https://www.no2id.net

Currently showing the default Apache page

**Comment by adamamyl** [comment]
@jezuk thanks for noticing/reporting. fixed.
